<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="autonomous_bot">

    <xacro:property name="PI" value="3.14159"/>
    <xacro:property name="base_width" value="0.2"/>
    <xacro:property name="base_length" value="0.3"/>
    <xacro:property name="base_height" value="0.05"/>
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_length" value="0.04"/>
    <xacro:property name="wheel_separation" value="0.24"/>

    <link name="base_link">
        <visual>
            <geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry>
            <material name="blue"><color rgba="0.2 0.2 0.8 1"/></material>
        </visual>
        <collision>
            <geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry>
        </collision>
        <inertial>
            <mass value="2.0"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.02" iyz="0.0" izz="0.02"/>
        </inertial>
    </link>

    <xacro:macro name="wheel" params="prefix reflect">
        <link name="${prefix}_wheel_link">
            <visual>
                <origin rpy="${PI/2} 0 0"/>
                <geometry><cylinder radius="${wheel_radius}" length="${wheel_length}"/></geometry>
                <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
            </visual>
            <collision>
                <origin rpy="${PI/2} 0 0"/>
                <geometry><cylinder radius="${wheel_radius}" length="${wheel_length}"/></geometry>
            </collision>
            <inertial>
                <mass value="0.2"/>
                <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.002"/>
            </inertial>
        </link>
        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="0 ${reflect * wheel_separation/2} 0" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <xacro:wheel prefix="left" reflect="1"/>
    <xacro:wheel prefix="right" reflect="-1"/>

    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0 0 ${base_height/2}"/>
    </joint>

    <link name="gps_link"/>
    <joint name="gps_joint" type="fixed">
        <parent link="base_link"/>
        <child link="gps_link"/>
        <origin xyz="${base_length/3} 0 ${base_height}"/>
    </joint>
    
    <link name="laser_link">
        <visual>
            <geometry><box size="0.03 0.03 0.03"/></geometry>
            <material name="red"><color rgba="1 0 0 1"/></material>
        </visual>
    </link>
    <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_link"/>
        <origin xyz="${base_length/2 - 0.015} 0 ${base_height/2}"/>
    </joint>

    <gazebo>
        <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
            <ros>
                <namespace>/</namespace>
                <remapping>cmd_vel:=cmd_vel</remapping>
                <remapping>odom:=odom</remapping>
            </ros>
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>
            <wheel_separation>${wheel_separation}</wheel_separation>
            <wheel_diameter>${2 * wheel_radius}</wheel_diameter>
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_link</robot_base_frame>
        </plugin>

        <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
            <ros>
                <namespace>/</namespace>
                <remapping>~/out:=imu</remapping>
            </ros>
            <initial_orientation_as_reference>false</initial_orientation_as_reference>
        </plugin>

        <plugin name="gps_plugin" filename="libgazebo_ros_gps_sensor.so">
            <ros>
                <namespace>/</namespace>
                <remapping>~/out:=gps/fix</remapping>
            </ros>
        </plugin>

        <plugin name="laser_plugin" filename="libgazebo_ros_ray_sensor.so">
            <ros>
                <namespace>/</namespace>
                <remapping>~/out:=scan</remapping>
            </ros>
            <output_type>sensor_msgs/LaserScan</output_type>
            <frame_name>laser_link</frame_name>
            <sensor type="ray">
                <pose>0 0 0 0 0 0</pose>
                <visualize>true</visualize>
                <update_rate>10</update_rate>
                <ray>
                    <scan>
                        <horizontal>
                            <samples>360</samples>
                            <resolution>1</resolution>
                            <min_angle>-${PI}</min_angle>
                            <max_angle>${PI}</max_angle>
                        </horizontal>
                    </scan>
                    <range>
                        <min>0.1</min>
                        <max>12.0</max>
                        <resolution>0.01</resolution>
                    </range>
                </ray>
            </sensor>
        </plugin>
    </gazebo>
</robot>